import { useEffect, useRef, useState } from 'react'
import { ArrowUpRight, ChevronRight, CircleDollarSign, LayoutDashboard, Wallet, ArrowLeftRight, Target, ChartNoAxesCombined, Plus, X, Pencil, Trash2, ShieldCheck } from 'lucide-react'
import { type FinanceData, type Transaction, type Category, cents, money, dateLabel, totals, monthlyReport, emptyData } from './lib/finance'
import { loadData, saveData } from './lib/storage'
import { Card, Metric, Progress } from './components/ui'
import './App.css'
const navigation = [{ name: 'Dashboard', icon: LayoutDashboard }, { name: 'Budget', icon: Wallet }, { name: 'Transactions', icon: ArrowLeftRight }, { name: 'Goals', icon: Target }, { name: 'Insights', icon: ChartNoAxesCombined }]
const today = () => new Date().toLocaleDateString('en-CA')
type Modal = 'paycheck' | 'category' | 'transaction' | null
function App() {
  const dialogRef = useRef<HTMLElement>(null)
  const returnFocus = useRef<HTMLElement | null>(null)
  const [initial] = useState(() => { try { return { data: loadData(), error: '' } } catch { return { data: structuredClone(emptyData), error: 'Saved data could not be read. It has not been overwritten. Fix or back up the browser storage before continuing.' } } })
  const [data, setData] = useState<FinanceData>(initial.data)
  const [error, setError] = useState(initial.error)
  const [page, setPage] = useState('Dashboard')
  const [selected, setSelected] = useState(data.periods[0]?.id ?? '')
  const [modal, setModal] = useState<Modal>(null)
  const [editing, setEditing] = useState<Transaction | null>(null)
  const [editingCategory, setEditingCategory] = useState<Category | null>(null)
  const [formError, setFormError] = useState('')
  const [month, setMonth] = useState(today().slice(0, 7))
  useEffect(() => {
    if (!modal) return
    const handler = (event: KeyboardEvent) => {
      if (event.key !== 'Tab') return
      const elements = dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input, select')
      if (!elements?.length) return
      const first = elements[0], last = elements[elements.length - 1]
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus() }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus() }
    }
    document.addEventListener('keydown', handler)
    return () => { document.removeEventListener('keydown', handler); returnFocus.current?.focus() }
  }, [modal])
  const period = data.periods.find(p => p.id === selected)
  const summary = period ? totals(period, data.transactions) : null
  const entries = data.transactions.filter(t => t.periodId === selected).sort((a, b) => b.date.localeCompare(a.date))
  function commit(next: FinanceData) { if (initial.error) return false; try { saveData(next); setData(next); setError(''); return true } catch { setError('Could not save your changes. Browser storage may be full or disabled. Changes were not applied.'); return false } }
  function open(value: Modal, transaction: Transaction | null = null, category: Category | null = null) { returnFocus.current = document.activeElement as HTMLElement; setEditing(transaction); setEditingCategory(category); setFormError(''); setModal(value) }
  function submit(event: React.SubmitEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget)
    try {
      const amount = cents(String(form.get('amount')))
      let next = data
      if (modal === 'paycheck') {
        if (amount === 0) throw new Error('Paycheck must be greater than zero.')
        const p = { id: crypto.randomUUID(), date: String(form.get('date')), income: amount, categories: [] }
        next = { ...data, periods: [...data.periods, p] }
        if (commit(next)) { setSelected(p.id); setModal(null) }; return
      }
      if (!period) throw new Error('Create a paycheck first.')
      if (modal === 'category') {
        const name = String(form.get('name')).trim()
        if (!name) throw new Error('Enter a category name.')
        if (period.categories.some(c => c.id !== editingCategory?.id && c.name.toLowerCase() === name.toLowerCase())) throw new Error('That category already exists in this paycheck.')
        const category = { id: editingCategory?.id ?? crypto.randomUUID(), name, allocation: amount, kind: String(form.get('kind')) as Category['kind'] }
        next = { ...data, periods: data.periods.map(p => p.id === selected ? { ...p, categories: editingCategory ? p.categories.map(c => c.id === category.id ? category : c) : [...p.categories, category] } : p) }
      } else {
        if (!amount) throw new Error('Transaction must be greater than zero.')
        const description = String(form.get('description')).trim()
        if (!description) throw new Error('Enter a description.')
        const categoryId = String(form.get('category'))
        if (!period.categories.some(c => c.id === categoryId)) throw new Error('Select a budget category.')
        const transaction = { id: editing?.id ?? crypto.randomUUID(), periodId: selected, categoryId, date: String(form.get('date')), description, amount }
        next = { ...data, transactions: editing ? data.transactions.map(t => t.id === editing.id ? transaction : t) : [...data.transactions, transaction] }
      }
      if (commit(next)) setModal(null)
    } catch (e) { setFormError(e instanceof Error ? e.message : 'Please check your entries.') }
  }
  const categoryList = <div className="categories">{period?.categories.length ? period.categories.map((c, i) => <div className="category" key={c.id}><div className={`category-icon color-${i % 4}`}><Wallet size={18} /></div><div className="category-body"><div className="row"><strong>{c.name}</strong><span>{money(summary!.spentIn(c.id))} <span className="muted">/ {money(c.allocation)}</span></span></div><Progress spent={summary!.spentIn(c.id)} allocated={c.allocation} /><div className="row small muted"><span>{c.kind === 'reserved' ? 'Reserved expense' : c.kind === 'savings' ? 'Planned savings' : 'Spending budget'}</span><span className={summary!.spentIn(c.id) > c.allocation ? 'negative' : ''}>{money(c.allocation - summary!.spentIn(c.id))} left</span></div></div>{page === 'Budget' && <button className="icon-button" aria-label={`Edit ${c.name}`} onClick={() => open('category', null, c)}><Pencil size={16} /></button>}</div>) : <div className="empty"><Wallet /><h3>Give every dollar a purpose</h3><p>Add spending categories, reserved bills, and planned savings to your paycheck.</p><button className="secondary" onClick={() => open('category')}>Create a category</button></div>}</div>
  function transactionList(list: Transaction[]) { return list.length ? <div className="transaction-list">{list.map(t => <div className="transaction" key={t.id}><div className="transaction-icon"><ArrowUpRight size={18} /></div><div className="transaction-description"><strong>{t.description}</strong><span className="muted small">{period?.categories.find(c => c.id === t.categoryId)?.name} · {dateLabel(t.date)}</span></div><strong className="transaction-amount">−{money(t.amount)}</strong>{page === 'Transactions' && <div className="row"><button className="icon-button" aria-label={`Edit ${t.description}`} onClick={() => open('transaction', t)}><Pencil size={16} /></button><button className="icon-button" aria-label={`Delete ${t.description}`} onClick={() => { if (window.confirm(`Delete “${t.description}”?`)) commit({ ...data, transactions: data.transactions.filter(x => x.id !== t.id) }) }}><Trash2 size={16} /></button></div>}</div>)}</div> : <div className="empty compact"><ArrowLeftRight /><h3>A fresh start</h3><p>Your transactions will appear here as you track spending.</p></div> }
  const report = monthlyReport(data, month)
  return <div className="app"><aside className="sidebar"><a className="brand" href="#" onClick={e => { e.preventDefault(); setPage('Dashboard') }}><span className="brand-symbol"><ChartNoAxesCombined size={23} /></span>paywise<span className="brand-dot">.</span></a><div className="sidebar-caption">YOUR FINANCIAL SPACE</div><nav>{navigation.map(({ name, icon: Icon }) => <button key={name} className={page === name ? 'nav-item active' : 'nav-item'} onClick={() => setPage(name)}><Icon size={20} /><span>{name}</span>{page === name && <span className="nav-dot" />}</button>)}</nav><div className="sidebar-bottom"><div className="local-badge"><ShieldCheck size={20} /><div><strong>Your money, your space</strong><p>Stored privately in this browser</p></div></div><div className="profile"><div className="avatar">Y</div><div><strong>Your workspace</strong><p>Personal finance</p></div></div></div></aside>
    <div className="main-shell"><header className="topbar"><span className="breadcrumb">Workspace <ChevronRight size={14} /> <strong>{page}</strong></span><span className="local-tag"><span /> Local workspace</span></header><main><div className="page-heading"><div><div className="eyebrow">A LITTLE CLARITY. A LOT MORE CONTROL.</div><h1>{page === 'Dashboard' ? 'Your money, at a glance' : page === 'Budget' ? 'Make a plan for your paycheck' : page === 'Transactions' ? 'Every dollar, accounted for' : page === 'Goals' ? 'Make room for what matters' : 'See the bigger picture'}</h1><p className="muted">{page === 'Dashboard' ? 'Build good habits, one paycheck at a time.' : page === 'Budget' ? 'Set your priorities before your money goes anywhere.' : page === 'Transactions' ? 'Track expenses and keep your plan up to date.' : page === 'Goals' ? 'Your savings journey starts with a plan.' : 'Monthly reporting, powered by your actual entries.'}</p></div><button className="primary" disabled={!!initial.error} onClick={() => open('paycheck')}><Plus size={17} /> Add paycheck</button></div>
    {error && <div role="alert" className="alert">{error}</div>}
    <div className="period-bar"><div className="row"><span className="period-icon"><Wallet size={17} /></span><div><strong>Pay period</strong><span className="muted small period-sub">Choose a paycheck to review its plan</span></div></div><select aria-label="Selected paycheck" value={selected} onChange={e => setSelected(e.target.value)}><option value="" disabled>{data.periods.length ? 'Select paycheck' : 'No paychecks yet'}</option>{[...data.periods].sort((a, b) => b.date.localeCompare(a.date)).map(p => <option key={p.id} value={p.id}>{dateLabel(p.date)} · {money(p.income)}</option>)}</select></div>
    {!period && page !== 'Insights' ? <Card className="welcome"><span className="welcome-icon"><CircleDollarSign size={36} /></span><span className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h2>A clear plan for your next paycheck.</h2><p>Start with your take-home pay. Set aside bills and savings,<br className="desktop" /> then know exactly what you can spend.</p><button className="primary" disabled={!!initial.error} onClick={() => open('paycheck')}><Plus size={18} /> Create your first paycheck</button><div className="welcome-steps"><span><b>01</b> Add your paycheck</span><span><b>02</b> Plan your categories</span><span><b>03</b> Track your spending</span></div></Card> : <>
    {page === 'Dashboard' && summary && <><div className="metrics"><Metric label="Paycheck income" value={period!.income} detail="Take-home pay for this period" /><Metric label="Total spent" value={summary.spent} detail={`${entries.length} recorded expense${entries.length === 1 ? '' : 's'}`} /><Metric label="Spending budget left" value={summary.remaining} detail="Spending allocations minus expenses" /><Metric label="Available money" value={summary.available} detail="After expenses, reserved bills & savings" accent /></div><div className="dashboard-grid"><Card><div className="section-heading"><div><h2>Paycheck plan</h2><p className="muted small">A place for every dollar.</p></div><button className="text-button" onClick={() => setPage('Budget')}>Manage budget <ChevronRight size={15} /></button></div>{categoryList}<div className="card-footer row"><span className="muted">Unallocated money</span><strong className={summary.unallocated < 0 ? 'negative' : 'positive'}>{money(summary.unallocated)}</strong></div></Card><Card className="cash-card"><span className="eyebrow">THE BIG PICTURE</span><h2>Your paycheck breakdown</h2><div className="donut" style={{ background: `conic-gradient(#6ee7b7 0% ${period!.income ? Math.min(100, summary.spent / period!.income * 100) : 0}%, #25383c 0% 100%)` }}><div><span className="small muted">Recorded expenses</span><strong>{money(summary.spent)}</strong></div></div><div className="row"><span className="muted"><i className="legend-dot" /> Spent</span><strong>{money(summary.spent)}</strong></div><div className="row"><span className="muted"><i className="legend-dot dim" /> Income less expenses</span><strong>{money(period!.income - summary.spent)}</strong></div><p className="small muted chart-note">Reservations reduce available money even before you pay a bill.</p></Card></div><Card><div className="section-heading"><div><h2>Recent transactions</h2><p className="muted small">The little things add up.</p></div><button className="text-button" onClick={() => setPage('Transactions')}>View all <ChevronRight size={15} /></button></div>{transactionList(entries.slice(0, 5))}</Card></>}
    {page === 'Budget' && summary && <><div className="metrics three"><Metric label="Paycheck income" value={period!.income} detail="Your starting point" /><Metric label="Total allocated" value={summary.allocated} detail="Spending, reserved bills & savings" /><Metric label="Unallocated money" value={summary.unallocated} detail={summary.unallocated < 0 ? 'Your plan exceeds this paycheck' : 'Ready to give a purpose'} accent /></div>{summary.unallocated < 0 && <div className="alert">Your allocations exceed your income. Edit a category to bring your plan back into balance.</div>}<Card><div className="section-heading"><div><h2>Budget categories</h2><p className="small muted">Allocations belong to this paycheck only.</p></div><button className="secondary" onClick={() => open('category')}><Plus size={16} /> Add category</button></div>{categoryList}</Card><p className="small muted explanation">Available money = income − all recorded expenses − remaining reserved bills and savings. Spending budget left includes spending categories only. Add two paychecks per month, or any other schedule; review older plans with the paycheck selector.</p></>}
    {page === 'Transactions' && <Card><div className="section-heading"><div><h2>Transactions</h2><p className="small muted">Expenses assigned to your selected paycheck.</p></div><button className="primary" disabled={!period?.categories.length} onClick={() => open('transaction')}><Plus size={17} /> Add expense</button></div>{!period?.categories.length && <p className="small muted">Create a category in Budget before adding an expense.</p>}{transactionList(entries)}</Card>}
    {page === 'Goals' && <Card><div className="section-heading"><div><h2>Planned savings</h2><p className="muted">Your savings allocations for this paycheck.</p></div><Target className="positive" /></div>{period?.categories.filter(c => c.kind === 'savings').length ? period.categories.filter(c => c.kind === 'savings').map(c => <div className="goal" key={c.id}><Target size={23} /><div><h3>{c.name}</h3><p className="muted small">Planned contribution · not a verified account balance</p></div><strong>{money(c.allocation)}</strong></div>) : <div className="empty"><Target /><h3>What are you saving for?</h3><p>Create a category with the “Planned savings” type in Budget.</p><button className="secondary" onClick={() => setPage('Budget')}>Plan savings</button></div>}<p className="small muted explanation">Target amounts, deadlines, and balances across paychecks are a future milestone.</p></Card>}
    {page === 'Insights' && <><Card className="section-heading"><div><h2>Monthly cash flow</h2><p className="small muted">Income by paycheck date; expenses by transaction date.</p></div><input type="month" aria-label="Report month" value={month} onChange={e => setMonth(e.target.value)} /></Card><div className="metrics three"><Metric label="Monthly income" value={report.income} detail="Recorded paychecks" /><Metric label="Monthly expenses" value={report.spending} detail="Recorded transactions" /><Metric label="Net cash flow" value={report.net} detail="Income minus recorded expenses" accent /></div><Card><h2>A clearer picture over time</h2><p className="muted explanation">These totals reflect only what you enter. Savings reservations are plans, not bank transfers. Trends and richer category reports will grow from this foundation.</p></Card></>}
    </>}
    <footer><ShieldCheck size={14} /> Browser storage only · USD · No bank connection</footer></main></div>
    {modal && <div className="modal-backdrop" onClick={e => { if (e.target === e.currentTarget) setModal(null) }}><section ref={dialogRef} className="modal card" role="dialog" aria-modal="true" aria-labelledby="modal-title" onKeyDown={e => { if (e.key === 'Escape') setModal(null) }}><div className="section-heading"><h2 id="modal-title">{modal === 'paycheck' ? 'Add a paycheck' : modal === 'category' ? editingCategory ? 'Edit category' : 'Create a category' : editing ? 'Edit expense' : 'Add an expense'}</h2><button className="icon-button" aria-label="Close dialog" onClick={() => setModal(null)}><X size={20} /></button></div><form onSubmit={submit}>{modal === 'paycheck' && <p className="muted small">Enter take-home pay. Each paycheck gets its own budget, on any schedule.</p>}{modal === 'category' ? <><label>Category name<input autoFocus name="name" required maxLength={80} defaultValue={editingCategory?.name} placeholder="e.g. Groceries" /></label><label>Allocation type<select name="kind" defaultValue={editingCategory?.kind ?? 'spending'}><option value="spending">Spending budget</option><option value="reserved">Reserved expense / bill</option><option value="savings">Planned savings</option></select></label></> : <label>Date<input autoFocus type="date" name="date" required defaultValue={editing?.date ?? today()} /></label>}<label>{modal === 'category' ? 'Allocation' : modal === 'paycheck' ? 'Take-home amount' : 'Expense amount'} (USD)<input name="amount" required inputMode="decimal" placeholder="0.00" defaultValue={editing ? (editing.amount / 100).toFixed(2) : editingCategory ? (editingCategory.allocation / 100).toFixed(2) : undefined} /></label>{modal === 'transaction' && <><label>Description<input name="description" required maxLength={120} defaultValue={editing?.description} placeholder="e.g. Weekly groceries" /></label><label>Category<select name="category" required defaultValue={editing?.categoryId ?? period?.categories[0]?.id}>{period?.categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label></>}{formError && <p className="negative" role="alert">{formError}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={() => setModal(null)}>Cancel</button><button type="submit" className="primary" disabled={!!initial.error}>Save {modal === 'transaction' ? 'expense' : modal}</button></div></form></section></div>}
  </div>
}
export default App
